### ISSUE TITLE
Allow 'Shuffle Lines' to work on selection only

### ISSUE THREAD

**Issue by randallhedglin** [ingorichter/brackets-sort-text#10]
Hello,

I enjoy your plugin very much and use it extensively to sort lines of data.  One feature that I think would be useful would be to have the option of applying the 'Shuffle Lines' action to only the current selection rather than the entire document.  I use this feature to randomize sets of data in a larger document, and as it is, I have to copy and paste the lines into a new document, randomize them, and then copy and paste the shuffled lines back into my original document.  It's a tedious process when there are many sets of data to be randomized!

Thank you.

**Comment by ingorichter** [comment]
Thank you for the feedback. Let me see why I forgot to implement that feature ;-)
I believe that it shouldn't be that difficult to add

**Comment by ingorichter** [comment]
@randallhedglin thank you for the suggestion. I fixed/implemented support to shuffle lines in a selection. Unfortunately, the brackets extension registry doesn't have any disk space available at this time and I was unable to upload that release. I created a release here that you can use to try it out.

**Comment by randallhedglin** [comment]
Wonderful, thank you!
    On Thursday, June 18, 2020, 01:25:04 AM EDT, Ingo Richter <notifications@github.com> wrote:  
 
 


@randallhedglin thank you for the suggestion. I fixed/implemented support to shuffle lines in a selection. Unfortunately, the brackets extension registry doesn't have any disk space available at this time and I was unable to upload that release. I created a release here that you can use to try it out.
