### ISSUE TITLE
extension not loading

### ISSUE THREAD

**Issue by markhillard** [ingorichter/brackets-sort-text#7]
Hey there, I love this extension and use it all the time, especially in CSS files since I'm OCD and like to alphabetize my properties. However recently I've been running into an issue where the extension is simply not loading. I checked dev tools and saw this in console:

```
Attempting to register a command with a missing name, id, or command function:undefined
de.richter.brackets.extension.brackets-sort-text.sortLines
```

![errors](https://cloud.githubusercontent.com/assets/8247756/8580991/cd93c30c-258b-11e5-9df9-0135b33c6017.png)

What's strange is when I remove it and re-install it... it works fine for that session. But if I close or reload Brackets the options disappear from the "Edit" menu and I'm seeing the errors noted above in console.

I've been running the latest version of Brackets for a while now so I'm not sure what changed, other than I've been trying out some new extensions. Have you ever seen this before?

**Comment by FlouksBerlin** [comment]
Having the exact same problem with this extension. It works after reinstalling for the session. But if I close or reload Brackets it's gone.

**Comment by markhillard** [comment]
@ingorichter any idea what might be causing this?

**Comment by ingorichter** [comment]
This seems to happen only on Windows. On OSX I haven't seen this. I'm going to inspect this on my Windows machine tomorrow morning, when I'm back to in the office.

**Comment by markhillard** [comment]
Ok, great. I tried searching for this particular error and it appears it has something to do with `CommandManager`... http://brackets.io/docs/current/modules/command/CommandManager.html.

I wish I could help more but I've never developed a Brackets extension.

**Comment by ingorichter** [comment]
@FlouksBerlin & @markhillard does the same happen, if you remove all other extensions? I've tried to repro on Windows 8.1 and it works fine for me. I have a brand new install and this is the only extension installed so far. I'd like to find out what happens on your machine. Perhaps you can send me the list of extensions on your machine and try to repro with the same set of extensions, if you don't have the time for it.

**Comment by markhillard** [comment]
Here are the extensions I currently have installed:

- Beautify
- Brackets Icons
- Brackets Sort Text
- colorHints
- CSSLint
- Display Shortcuts
- Emmet
- HTMLHint
- Indent Guides
- Inline Image CSS or HTML Image Tag
- Jade Syntax Highlighting
- Join Lines
- JSHint
- JSONLint Extension for Brackets
- Markdown Preview
- Minifier
- Open In Browser
- Scroll Arrows
- Whitespace Normalizer

I haven't tried removing all other extensions. Is it possible for an extension to interfere with another?

**Comment by ingorichter** [comment]
Thanks @markhillard. I'll try to repro this with your set of extensions.
Yes, we had some extensions in the past that somehow interfered which each other.

**Comment by markhillard** [comment]
No problem @ingorichter. Thanks for taking the time to look at this.

**Comment by ingorichter** [comment]
@markhillard great, with your set of extensions I'm able to reproduce this issue. Now I need to figure out what happens here.

**Comment by ingorichter** [comment]
Wow, there is some serious s**t going on. The extension can't be loaded anymore, since the `nls` folder containing all the strings disappears. I have never seen this before and this might be a bigger issue. I'm still investigating this and hope to find the root cause.

**Comment by ingorichter** [comment]
This happens too on OSX. Luckily nothing system specific.

**Comment by ingorichter** [comment]
Okay, the folder wasn't deleted. Devtools didn't show the `nls` folder, since nothing was loaded from it.

**Comment by markhillard** [comment]
Glad you were able to dupe the issue @ingorichter. I was just going through some extensions that I rarely use and figured I'd take the opportunity to test your extension by reloading brackets after their removal. By sheer luck, after removing this one (https://github.com/wylst/brackets-minifier) on the first try I'm seeing that your extension is now loading properly, even after a full refresh.

I found this PR (https://github.com/wylst/brackets-minifier/pull/19) and it was for multilingual support, so I'm wondering if it has to do with `strings.js` and/or language conflicts. Wild guess on my part, but figured I'd let you know.

**Comment by ingorichter** [comment]
That's was a great hint. And it's crazy. As you said, disabling the [minifier](https://github.com/wylst/brackets-minifier) extension resolves the issue. So, when the minifier extension is loaded, `String = require("strings")` will load `uglify.js`. I don't understand what the minifier extension is doing to change the loading behavior of require.

**Comment by markhillard** [comment]
Yeah that's really weird. Not sure either. In that PR I referenced there's a new/better version of the minifier at https://github.com/abagshaw/brackets-minifier and that one seems to play nice.

**Comment by ingorichter** [comment]
Although I don't see which change might have caused the fix... This version of the extension has all dependencies updated. Perhaps uglifyjs didn't play well and the updated version fixed this issue.

**Comment by ingorichter** [comment]
And uglifyjs is not injected via script tag into the DOM. The new extension runs uglifyjs as node extension. That might explain why it's now working.

**Comment by markhillard** [comment]
Makes sense. Well feel free to close this issue out. Thanks again for your work. Great extension by the way.
